# -*- coding: utf-8 -*-
"""basic_revision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-So7sEvHvuM7A-WM9IX4NZEHGYbHbhpF
"""

!pip install pandas as pd

!pip install numpy as np

!pip install matplotlib.pyplot as plt

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

!pip install scikit-learn

import sklearn as sks

df = pd.read_csv('/content/house_price_linear_regression.csv')

df.head(5)

df.tail(5)

df.isnull()

plt.xlabel('price of house ')
plt.ylabel('areaof house')
plt.scatter(df['Area_sqft'],df.Price_lakhs, color='blue', marker = "*")

from  sklearn import linear_model

reg = linear_model.LinearRegression()

reg.fit(df[['Area_sqft']],df.Price_lakhs)

reg.predict([[1600]])

df1= pd.read_csv('/content/area_only_50_entries (1).csv' )

df1.head(3)

price = reg.predict(df1)

df1['price']= price

df1.head(5)

df1.to_csv('prediction_csv1.csv', index = False)

